# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            HaYuneJ
description:      'Hyoil & TechPang Dev'
baseurl:          /

github:
  repo:           https://github.com/PigTongTong
